# Generated by Django 4.2.5 on 2023-10-11 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regandloginapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reg',
            name='emailpassword',
        ),
    ]
